### ISSUE TITLE
Wat gebeurt er als de bank ons geen lening wil geven?

### ISSUE THREAD

**Issue by Ricostyle21** [Plan-van-Bouw/ALV_November_2023#10]
Wat gaan we doen als de bank ons geen lening wil geven of ons niet een lening van de benodigde hoogte wil geven?

**Comment by Lkeurentjes** [comment]
Dat is een situatie die we jammergenoeg niet zelf in de hand hebben. Als de bank geen lening wil geven kunnen we natuurlijk niet gaan bouwen. Afhankelijk van wat de bank zegt en of een lagere lening wel mogelijk zou zijn, kunnen we nog een keer naar besparings opties kijken. Als er besparingen nog zijn van een "lager niveau dan het Technisch Ontwerp" (bijvoorbeeld een grote verandering in de plattegrond of gevels) dan moeten we waarschijnlijk vanaf die fase "opnieuw"  beginnen wat veel extra kosten met zich mee brengt.

Dus afhankelijk van wat de bank zegt wordt het dan niet bouwen of iig vertraagd bouwen. We hebben wel al ons eerste gesprek bij de bank gepland voor het inleveren van de omgevingsvergunning & financieel advies bij het aanvragen van de lening van Oud leden en de TU Delft. Dus we gaan ervanuit dat we een goed doordacht plan hebben en mocht het stuklopen niet daarvoor al onnodig veel geld uitgeven.
