### ISSUE TITLE
Waar komen de fietsen te staan?

### ISSUE THREAD

**Issue by DaniqueBuchner** [Plan-van-Bouw/ALV_November_2023#11]
vooral bij grote feesten, dat brandroutes ook vrij blijven (iig naar het vlot toe)

**Comment by PvBouw** [comment]
De fietsenrekken zijn nu ingetekend naast de Beuk, dichtbij het hek van het vlot. Dit zal niet genoeg zijn bij grote druk op de borrelavonden, dus we nog kijken of we op andere plekken fietsen zouden kunnen plaatsen. Bijvoorbeeld de inhammen bij de brug.
