### ISSUE TITLE
Is het financiële plaatje al rond?

### ISSUE THREAD

**Issue by MarnixTijhuis** [Plan-van-Bouw/ALV_November_2023#12]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by Lkeurentjes** [comment]
Ja! (of nouja zo goed als) Ongeveer Woensdag zullen de stukken worden geupload op de stukken drive. Deze omvast een begroting, een lening & een (voorlopige) opbouw voor het jaarbedrag. Er zijn (zeker voor de lening) wel een aantal aannames gemaakt, die nog richting de volgende ALV kunnen veranderen, maar voor de rest is het zo goed als rond!
