### ISSUE TITLE
Wanneer gaat de eerste steen gelegd worden?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#13]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by Lkeurentjes** [comment]
als het goed is is je vraag al beantwoord in https://github.com/Plan-van-Bouw/ALV_November_2023/issues/2 Als dat niet zo is laat dan vooral een reactie achter!

**Comment by MarnixTijhuis** [comment]
@wbakkeren ga jij die eerste steen leggen?
