### ISSUE TITLE
Is een budget van 16000 euro voor de inrichting van het krachthonk realistisch?

### ISSUE THREAD

**Issue by markfromthemountain** [Plan-van-Bouw/ALV_November_2023#14]
In figuur 3.6 staat dat voor de inrichting van de KT ruimte een budget is van 16119 euro. Waarop is dit bedrag gebaseerd?

**Comment by Lkeurentjes** [comment]
Heeey Mark, dit is gebaseerd op wat de KvB (voorheen krachtrainingswerkgroep) heeft uitgezocht en aan hun heeft doorgegeven. Zij hebben er dus over nagedacht wat er nodig is en daarop een begroting gebaseerd. Ik zal je vraag nog even doorspelen voor een lijstje met wat ongeveer het plan is van die 16k.

**Comment by vossemeijssen** [comment]
Het doel van de KT ruimte is om ongeveer een replica te worden van de "Strength" ruimte in X. Dit betekent dat de oefeningen die daar gedaan worden, ook op Proteus gedaan kunnen worden. We hebben een lijst gemaakt van materiaal wat hiervoor nodig is, en op basis van advies van Malin (KT begeleidster) en Niels (programma manager bij X) hebben we kritisch gekeken naar de kwaliteit van dit materiaal. Een 20kg-stang kan bijvoorbeeld 120 of 1200 euro kosten. 

Uiteindelijk kwam hieruit een begroting, die zegt dat we voor ongeveer 16000 euro krachthonk kunnen inrichten. Deze prijs is natuurlijk een schatting, en kan nog schommelen onder invloed van inflatie en leuke deals.
