### ISSUE TITLE
Wat staat er nu precies in ons langdurige contract met X over het verplicht afnemen van fitness abonnementen? 

### ISSUE THREAD

**Issue by Nieksebas** [Plan-van-Bouw/ALV_November_2023#15]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by DaniqueBuchner** [comment]
In het contract met X hebben we alleen afspraken gemaakt over het afnemen van reguliere X abonnementen, over het afnemen van de fitness supplementen zijn dus geen afspraken gemaakt.
Nu moet je als wedstro/iemand die wil krachttrainen een supplement bij X kopen, als de aanbouw er is hoef je dus niet meer een supplement aan te schaffen en kan je lekker op Proteus-Eretes komen krachttrainen!

**Comment by Nieksebas** [comment]
Is er ook gekeken naar de extra kosten die er dan bijkomen voor naar proteus halen voor een kracht trainer?

**Comment by Lkeurentjes** [comment]
We hebben hier al een eerste overleg over gehad met X, maar het is nu vooral orrienterend geweest. Zij hebben geen bezwaar tegen een krachttrainer inhuren op eigen locatie en betalen dan nogsteeds dezelfde vergoeding. Dit zou Malin kunnen zijn of als zij niet wil iemand anders. Als we hetzelfde aantal uren afnemen zal de prijs niet veranderen. Daar zit natuurlijk de kleine side note in dat we op dit moment voor de helft van ieder uur betalen omdat we alle uren samen delen met laga. Doordt we dan niet samen delen met laga wordt de capaciteit per uur wel hoger en bovendien kunnen we in tegen stelling tot nu zelf de KT dagen beslissen. De PvB en de CW en het presidium gaan met de vervolg stappen bezig tijdens de volgende fase(s), er zal dan op basis van input van hun/de cv en de desbetreffende krachttrainer worden uitgezocht wat dan de beste optie is voor proteus.
