### ISSUE TITLE
Halen we het minimaal aantal X-abonnementen als wedstro's die niet meer afnemen? 

### ISSUE THREAD

**Issue by MarnixTijhuis** [Plan-van-Bouw/ALV_November_2023#16]
![image](https://github.com/Plan-van-Bouw/ALV_November_2023/assets/151046053/c31fb1eb-3f6e-4e82-998b-926779aa95a0)
Deze besparing zorgt voor een stuk minder X-abonnementen, halen we dan het minimaal aantal X-abonnementen dat X van ons wilt hebben?

**Comment by Lkeurentjes** [comment]
Heeey Marnix,

Scherp gezien, het is een typefout van ons in de ALV stukken :(. Er moet staan dat een fitnesskaart niet meer nodig is, dus dat die kosten zullen vervallen. We gaan het ook gelijk aanpassen in de stukken. Maar om je vraag nog te beantwoorden. We komen er niet onderuit dat Wedstro's sportkaarten afnemen. In ons contract zijn verschillende soorten roeiers gedefinieerd waar we een bepaald "sponsor" bedrag van krijgen voor X. Dit krijgen we dan van hun in de vorm van vergoeding voor profcoaching en bijvoorbeeld boten. Wedstro's zullen dus wel altijd een sportkaart moeten blijven afnemen, iig de contractduur van het huidige contract (nog 12 jaar). Hopelijk beantwoord dat je vraag.

**Comment by MarnixTijhuis** [comment]
Dat is duidelijk :)
