### ISSUE TITLE
Is het jaarlijkse bedrag dat we vrij moeten spelen (145000 eu volgens de begroting) niet hoger dan in de enquête werd gegeven?

### ISSUE THREAD

**Issue by chielvanbaardwijk** [Plan-van-Bouw/ALV_November_2023#17]
In de enquete die we kregen om onze keuzes te geven hoe we geld vrij zouden spelen voor de bouw waren de opties 70.000, 100.000, en 130.000 euro. Nu zie ik in de begroting 145.000 euro staan, waar komt dit verschil vandaan?

Groetjes,
Chiel

**Comment by Lkeurentjes** [comment]
Heeey Chiel,

Ik snap de verwarring, heel kort door de bocht wat de orginele berkening Proteus spaart nu al jaarlijks 50k + de leden vullen een equete in van hoe je daarboven op nog 70k 100k of 130k bespaar. Hiermee komt dan het totale jaarbedrag wat na de enquete is vrijgemaakt op 120k, 150k, en 180k. De 180 k werd nog door weinig mensen gedragen, dus ons doel was om onder de 150k te blijven en het liefst door middel van besparingen daar zo ver mogelijk onder te komen. Dat is een soort van gelukt op dit moment. Maar het verschil daartussen is dus eigenlijk die "start" 50k.

Beantwoord dat een beetje je vraag?

**Comment by chielvanbaardwijk** [comment]
Hoi Lisa,

Dat verduidelijkt veel, dankjewel voor je antwoord!
