### ISSUE TITLE
In de stukken (p20) staat dat er nog een besparingsronde gaat komen van rond de 3 ton. Waar gaat precies op bespaard worden en wat heeft dit voor impact op de vergunning die aangevraagd moet worden obv het huidige ontwerp?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#18]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by THeij20** [comment]
De besparing van 3 ton zijn we al deels mee begonnen. Maar de grootste besparing zal zitten in de installaties en verder het besparen op kleinere ontwerp dingen. Dit zal verder geen effect op de omgevingsvergunning, omdat we voor de aanvraag al de besparingen zullen doen en na de aanvraag zullen we mogelijk nog kleine besparingen binnen het gebouw doen, maar dan zal er aan het ontwerp van buiten niks meer veranderen.
