### ISSUE TITLE
Bij de kosten voor diensten in de tabellen op p20 en p21 van de stukken staan 2 verschillende getallen, 315k en 263k. Waardoor komt dat verschil?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#19]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by Lkeurentjes** [comment]
Heeey Wouter, Dat verschil is €51.435 euro als ik het goed hebt. Als je het op pagina 25 kijkt zie je al waar het getal vandaan komt. Dat zijn de diensten die we al in vorig bestuursjaar/(-ren) hebben betaald. Omdat we dit geld al uit de voorziening is gehaald hoeven we die niet mee te nemen in de berekening voor de lening dit jaar, maar voor de volledigheid hebben we hem hier wel toegevoegd.

In totaal hebben we aan de diensten in de vorige fase ~150k betaald, hier van moeten we nog ~99.5k dit jaar afrekenen. Die gaat mee in het totale plaatje van de stichtingskosten voor de lening. De andere 51k is verbonden met een potje "al uitgegeven voor de bouw" Beantwoord dit je vraag?

Groetjes,
Lisa

**Comment by wbakkeren** [comment]
Yes, duidelijk! :)
