### ISSUE TITLE
Wanneer willen we starten met bouwen?

### ISSUE THREAD

**Issue by PvBouw** [Plan-van-Bouw/ALV_November_2023#2]

**Comment by Lkeurentjes** [comment]
Eigenlijk begint de fase "bouw" al na het ondertekenen van de overeenkomst in maart (en het daarvoor een aanbetaling doen, waarvoor we de lening nodig hebben). Het eerste deel van start bouw zal voornamelijk op de achtergrond gebeuren, omdat veel leveranciers dan levertijden hebben en productie tekeningen moeten maken en verwerken tot een product. Eind juli/begin Augustus kunnen dan de eerste dingen geleverd worden. Maar gezien de Bouwvak en de Owee zullen we wss pas de grond en Proteus overhoop trekken daarna. De keuze zal dan wss vallen op het weekend na de Owee beginnen.

**Comment by Nieksebas** [comment]
Was bij de stemming over verhoging van de contributie niet gesteld dat het alleen omhoog gaat als de eerste steen in dat jaar gelegd wordt?

**Comment by larsdevries6** [comment]
Deze zullen wij in het vragenrondje behandelen. Mochten wij het vergeten kan je hem altijd stellen
