### ISSUE TITLE
Is er in de risico analyse ook verder gekeken dan besparingen in het botenplan? Bijvoorbeeld het effect van minder leden als de contributie significant verhoogd wordt?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#20]

**Comment by Lkeurentjes** [comment]
Ja er zijn zeker Risico's maar en we hebben alles "krap" ingeschat ipv heel ruim. Zo'n inschatting is uiteindelijk netzo als een begroting, er gaat bij de een wat mhoog en bij de ander wat naar beneden en uiteindelijk speelt het ongeveer gelijk. Het geld wat we vrij maken voor de lening staat in het eerste jaar echt vast, maar zal daarna meegroeien met de vereniging en jaarlijks worden herzien. Eigenlijk vul je dan het jaarbedrag in je begroting in en ga je dan kijken hoe beleidstechnisch jij dat als bestuur rondspeelt. Hier zullen natuurlijk vaste dingen inzitten (de contributie mag je bijvoorbeeld niet zomaar veranderen), maar ook ruimte zijn voor beleid. Er is altijd een Risico dat we een hele grote tegenvaller hebben, minder leden, een slecht biercontract, en daar zijn al onze spaarplannen de buffer voor, waar het botenplan en de jaarlijkse bijdrage daarvan de grootste is. Maar ook de sponsoring van de TU, zouden we bijvoorbeeld ook als buffer voor risico's kunnen zien. BEantwoord dit je vraag?

**Comment by wbakkeren** [comment]
Niet helemaal eigenlijk, ik snap dat het allemaal onzeker is, maar juist daarom zou ik wat concretere inschattingen willen zien. Bijvoorbeeld met verschillende scenario's, stel het biercontract valt tegen, en de obligaties, en de staffel, en het ledenaantal... Voor mn gevoel zou je hier percentages aan moeten kunnen hangen met hoe waarschijnlijk ieder scenario is en de financiële gevolgen hiervan. Zeker omdat het over zo'n groot geldbedrag gaat, vind ik niet dat je er vanuit kan gaan dat het uiteindelijk 'ongeveer gelijk speelt', maar dat is misschien een verschil in mening.

**Comment by Lkeurentjes** [comment]
Heeey, ik zie dat er niemand meer had gereageerd op je reactie. We zijn hier mee bezig/gaan hier nog mee aan de slag. De aanpak is wel een klein beetje anders dan je voorstel. Ipv dat we zeggen wat als dit of wat als dat, doen we eigenlijk een range stellen hoeveel euro een financiele tegenvaller is en wat dan oplossingen zijn, we zullen dus voor de volgende ALV naast het jaarbedrag wat "officieel" wordt vastgelegd (bijvoorbeeld door stemming contributie verhoging, etc.) het lijstje wat we aanleveren doortrekken naar een x euro hoger bedrag wat er dan niet doorheen wordt gestemd omdat we dat op dat moment niet nodig hebben. Deze zal voortkomen uit alle enquetes en inspraak die we al hebben en evntueel nog meer verzamelen. We zullen dus eigenlijk een lijst opstellen waar we bij wijze van spreken tot een jaarbedrag van 2 ton komen, en pakken dan voor de ALV de bovenste x opties om door de ALV te halen, maar alle dingen die voor de rest op de lijst staan zullen dan in die volghorde ook globaal gezien de stappen zijn als er eentje die we daarvoor gebruiken wegvalt of verminderd. We hebben nu op dit moment ook al zo'n lijst gemaakt, als je wilt kunnen we die nog een keer laten zien.

Naar minder leden zullen we op verzoek van de ALV ook nog even los wat data en risico's en oplossingen op loslaten. In grote lijnen zal die overeenkomen met de lijst van hierboven, behalve dat er misschien iets gebalanceerder zal worden gekeken wanneer een "stap" leden geld kost en wanneer een "stap" de vereniging geld kost, dan wel door te "schaler te worden", dan wel door iets anders.
