### ISSUE TITLE
Kunnen jullie wat meer uitleggen waar ik naar kijk op p15-17 van de architect tekeningen (v01..v27)?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#21]

**Comment by thirzave** [comment]
Deze details laten zien hoe de wanden en vloeren zijn opgebouwd, en hoe die op elkaar aansluiten. Hierin kun je bijvoorbeeld zien hoe de isolatie doorloopt en hoe materialen aan elkaar bevestigd kunnen worden. Dit is vooral een onderwerp om uit te werken in de TO-fase.
