### ISSUE TITLE
Dingen als de inrichting van de keuken en commissiekamers, zit dat inbegrepen in de €3761 van 'Inrichting Gebouw'?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#22]

**Comment by larsdevries6** [comment]
Het bedrag voor de inrichting (+/- 37.6 k pro rata) is op het plaatje in 2 delen opgeslitst. Hiervoor hebben wij nu grofweg een 10/90% verhouding toegepast.
- Het ene deel gaat over het zelf doen van bijvoorbeeld de muren verven. 
- En het andere potje (die 3761 pro rata/ 3500 ex btw) is voor het kopen van stoelen, tafels en inrichting van de commisiekamers. 
Hier valt de inrichting van de keuken niet onder. De huidige materialen vanuit de keuken worden overgezet en dit wordt aangevuld met nieuwe werkbanken die betaald worden vanuit het keukenspaarplan.
