### ISSUE TITLE
Is er meer informatie beschikbaar of de duurzaamheid?

### ISSUE THREAD

**Issue by Jorn-Bor** [Plan-van-Bouw/ALV_November_2023#23]
Ik lees in het DO (als ik niet over iets heen heb gelezen) alleen 1 kleine paragraaf over duurzaamheid op p12. Ik vind deze paragraaf erg kort en had eigenlijk op meer informatie gehoopt, is dit nog ergens verder uitgewerkt?

Het belangrijkste wat ik mis is een duidelijk plan hoe dit gebouw (huidige + aanbouw) gasloos zou kunnen functioneren. Dit gebouw zal een tijdje staan, tot 2050 en verder lijkt me niet helemaal onrealistisch. Tegen die tijd moet het gebouw gasloos zijn, als hier nu al een duidelijk plan voor is en goed over nagedacht is, wordt deze overgang zo soepel en goedkoop mogelijk. Dat lijkt mij erg wenselijk.

**Comment by LisevE** [comment]
Hoi, goede vraag. Het uitgangspunt duurzaamheid komen voornamelijk naar voren in de materiaal keuzes en de installaties. Om geen gebruik meer te hoeven maken van gas wordt er al op inductie gekookt. Daarnaast zal het gebouw na de verbouwing verwarmt worden met een elektrische boiler. Dus de stap van het gas af wordt binnen dit project gemaakt.

**Comment by Jorn-Bor** [comment]
Dankjewel voor je antwoord. Erg goed om te horen dat we binnen dit bouw traject al van het gas af gaan, dat vind ik een hele mooie en belangrijke stap voor de vereniging, jammer dat het niet in het DO te lezen was, maar goed om te weten dat dit het geval is!
