### ISSUE TITLE
Hebben leden invloed op de keuze van de bank?

### ISSUE THREAD

**Issue by Jorn-Bor** [Plan-van-Bouw/ALV_November_2023#24]

**Comment by larsdevries6** [comment]
Tot op zekere hoogte wel. Wij gaan de gesprekken met de banken voeren om daar de mogelijkheden te verzamelen. Daarna zullen wij het beste aanbod uitzoeken en dit presenteren op de ALV. Hierover kan op de volgende bouw ALV (maart 2024) gestemd gaan worden als alles volgens planning loopt. Mocht je tips hebben of mee willen denken over de banklening kan je altijd contact met ons opnemen.

**Comment by Jorn-Bor** [comment]
maar kunnen we dan ook stemmen over de 3 aanboden, of alleen ja/nee op het door jullie gekozen beste aanbod

**Comment by larsdevries6** [comment]
Naar alle waarschijnlijkheid zullen wij met slechts één bank het hele traject doorlopen en dit gaan presenteren op de ALV. 
Echter is dit iets wat wij op dit moment ook nog niet zeker weten. Mochten we meerdere opties hebben zou het eventueel een keuze moment op de ALV kunnen worden. Verder zullen wij deze keuzes niet alleen gaan maken maar in samenspraak met het bestuur, de kascie, de SHaPE en de RvA

**Comment by Jorn-Bor** [comment]
Bedankt voor je antwoord, als het nog niet helemaal duidelijk is is het misschien een goed idee om te peilen of leden een voorkeur hebben voor een bepaalde bank. Ik zou het zelf heel jammer vinden als Proteus met ING, ANB of Rabo in zee gaat. Deze banken hebben duurzaamheid en mensenrechten namelijk niet bepaald hoog in het vaandel staan.
