### ISSUE TITLE
Is er rekening gehouden met de komst van de omgevingswet/wat voor een effect kan dit hebben op de bouw?

### ISSUE THREAD

**Issue by SamKnep05** [Plan-van-Bouw/ALV_November_2023#25]

**Comment by LisevE** [comment]
We willen na deze ALV de omgevingsvergunning zo snel mogelijk indienen als de meerderheid van de leden 'voor' heeft gestemd. Dan dienen we onze aanvraag nog in 2023 in bij de gemeente en hebben we niet te maken met de nieuwe omgevingswet. De stukken voor de vergunning zijn zo goed als klaar.
