### ISSUE TITLE
financiering bouw mbt aantal leden

### ISSUE THREAD

**Issue by ABovekerk** [Plan-van-Bouw/ALV_November_2023#26]
Om de bouw te kunnen betalen zal de contributie (blijvend) omhoog gaan en het gebouw voor ongeveer een heel jaar grotendeels onbruikbaar zijn. Hoe is er rekening gehouden met het scenario waar veel meer leden dan normaal zich zullen uitschrijven en minder nieuwe leden zich zullen inschrijven ivm de hogere contributie en/of het niet gebruik kunnen maken van het gebouw? Welk effect zou dit op de financiën van Proteus hebben?

**Comment by IngeMarieke** [comment]
Ja, het is een reeël scenario dat er zich meer leden zullen uitschrijven, dit weten we in ieder geval al voor de zomervakantie. We zouden er dan voor kunnen kiezen om er op aan te sturen om meer mensen in te gaan loten.  Het is lastig om precies te zeggen wat er gaat gebueren het is een beetje net als begroten soms wordt er iets minder en soms wordt er iets meer, en vaak compenseert elkaar dat. Mocht er eenmalig een risico ontstaan, dan hebben we een buffer door alle spaarplannen, mocht er structrueel een gat ontstaan, dan moet het dan ergens anders uit de begroting komen. Maar dat moeten we jaarlijks evalueren.
