### ISSUE TITLE
Uitkoop buren

### ISSUE THREAD

**Issue by BaukeBr** [Plan-van-Bouw/ALV_November_2023#28]
Er waren lange tijd plannen om de buren uit te kopen waar laatst wat voortgang mee was gemaakt. Waarom wordt dit niet gedaan in plaats van de aanbouw? Dat zou denk ik een stuk goedkoper en sneller zijn, en we zouden meer plek over houden op het fietsterrein voor bijvoorbeeld OWee feesten, iets waar PE bekend om staat.

**Comment by IngeMarieke** [comment]
Dit is inderdaad eerder overwogen en overleg over geweest, echter is dit financieel niet haalbaar

**Comment by Boumanp** [comment]
Wat is financieel niet haalbaar, hoorde dat de buurman een prijs had gegeven.

**Comment by BaukeBr** [comment]
Volgens de samenvatting gaat aanbouw zo’n 2,7 miljoen kosten. Welke kosten zitten er allemaal aan verbonden dat uitkoop niet mogelijk zou zijn in plaats van aanbouw? Of is deze mogelijkheid al een keer uitgewerkt en getoond.

**Comment by IngeMarieke** [comment]
> Wat is financieel niet haalbaar, hoorde dat de buurman een prijs had gegeven.

Orde grootte: even duur, dan wel duurder dan de aanbouw
