### ISSUE TITLE
Financiering voor het jaarbedrag

### ISSUE THREAD

**Issue by 90zaza** [Plan-van-Bouw/ALV_November_2023#29]
In de stukken is een tabel gecreeerd adhv een enquête om aan het jaarbedrag voor de bouw te komen. Wat is er gebeurd met de daarop volgende enquête om ipv verschillende plekken van besparing het gewoon te bereiken door flat-out de contributie voor iedereen met X bedrag te verhogen?

**Comment by larsdevries6** [comment]
Uit de contributie enquete is gebleken dat mensen akkoord zouden gaan met een stijging van 50 euro van de contributie. Echter is een hogere contributiestijging iets wat niet meer gedragen wordt door de leden. Hierdoor hebben wij de contributie wat hoger op de besparingslijst gezet, wat overeenkomt met dat +/- de helft van het jaarbedrag uit de contributieverhoging gehaald zal worden (45k uit de contributie van de 100k wat we extra moeten besparen).

**Comment by 90zaza** [comment]
Is er later nog gekeken naar of men deze enquete juist begrepen heeft? In de wandelgangen is gebleken dat veel mensen deze enquête begreep als contributie BOVENOP de besparingen van de vorige enquête, niet in plaats van. Ik denk dat dat het plaatje immens veranderd
