### ISSUE TITLE
Waarom geldt de bruikleenovereenkomst voor 10 jaar?

### ISSUE THREAD

**Issue by JasperBoogers** [Plan-van-Bouw/ALV_November_2023#30]
De lening loopt vooralsnog voor 15 jaar, dus waarom eerder de bruikleenovereenkomst stoppen?
Los daarvan, waarom überhaupt zo'n korte termijn?

**Comment by JasperBoogers** [comment]
Bruikleenovereenkomst tussen shape en pe bedoel ik

**Comment by larsdevries6** [comment]
Kom in de pauze even langs, dan kijken we er even naar.

**Comment by JasperBoogers** [comment]
Ik heb net van Mark Kievit gehoord dat de 10 jaar redelijk arbitrair gekozen is
