### ISSUE TITLE
Wat valt er allemaal onder het technische ontwerp?

### ISSUE THREAD

**Issue by Dux02** [Plan-van-Bouw/ALV_November_2023#31]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by IngeMarieke** [comment]
Onder het technische ontwerp valt met name de technische uitwerking van het definitieve ontwerp zoals vandaag wordt gepresenteerd. Het is dus vooral een fine-tune fase. Zometeen tijdens de presentatie zal Lisa dit uitgebreid toelichten, dus stel vooral vervolgvragen als er nog verdere onduidelijkheden zijn
