### ISSUE TITLE
Vergunning 

### ISSUE THREAD

**Issue by IgorGroot** [Plan-van-Bouw/ALV_November_2023#32]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg
Stemmen we niet meer over het aanvragen van een vergunning?

**Comment by IngeMarieke** [comment]
We stemmen over het ingaan van de nieuwe fase. Hierbij hoort het aanvragen van de omgevingsvergunning, maar ook het aanvragen van financiering bij de bank en het DO dus verder uitwerken. Echter zal dit wel in stappen gaan. Zo zullen we niet de omgevingsvergunning aanvragen voordat we financiering van de bank hebben. Heb ik zo je vraag beantwoord?
