### ISSUE TITLE
Hoe zijn de gesprekken tot nu toe met de bank gegaan? Hoe groot is de kans dat we geen lening krijgen?

### ISSUE THREAD

**Issue by RelatiefPE** [Plan-van-Bouw/ALV_November_2023#33]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by larsdevries6** [comment]
Op dit moment zitten we nog niet om de tafel met de bank. Deze gesprekken zullen volgende week plaats gaan vinden. Wel worden we ondersteund door een finance mannetje van de TU. Hij acht de kans aanwezig dat wij een lening kunnen krijgen, maar dit is op dit moment nog niet bekend.
