### ISSUE TITLE
Gaan we in een later stadium nog stemmen over hoe we de bouw gaan financieren?

### ISSUE THREAD

**Issue by Jornvanbeek** [Plan-van-Bouw/ALV_November_2023#34]
Met name over waar we het geld vandaan gaan halen om de lening af te betalen. Ik ga er vanuit dat dit tegelijkertijd gebeurt met het stemmen over de lening?

**Comment by larsdevries6** [comment]
Dat klopt. Op dit moment hebben wij een lijst opgesteld zodat ieder lid ook concreet kan zien wat welke besparingen voor iedereen gaan betekenen. Echter staat deze lijst nog niet vast maar is het wel gebaseerd op de enquete resultaten. 
Deze besparingen zullen op dezelfde stemming aan de orde komen als de lening
