### ISSUE TITLE
Waarop stemmen 

### ISSUE THREAD

**Issue by Tymen249** [Plan-van-Bouw/ALV_November_2023#35]
Betekent dat we vandaag wel stemmen of we het eens zijn met het huidige ontwerp. Als in, ik ben voor de aanbouw, maar tegen het ontwerp. Stem ik dan tegen?

**Comment by LisevE** [comment]
Je stemt vandaag voor de uitgave van het geld voor het technisch ontwerp en het aanvragen van de omgevingsvergunning, met het huidige ontwerp. Het ontwerp wordt niet/nauwelijks meer aangepast, de definitieve ontwerpfase is afgerond.
