### ISSUE TITLE
Hoe reëel is het dat we na aanvraag ook echt de vergunning krijgen? Wat gebeurd er met het geld als we worden afgewezen?

### ISSUE THREAD

**Issue by RelatiefPE** [Plan-van-Bouw/ALV_November_2023#36]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by IngeMarieke** [comment]
We gaan eerst een vooroverleg bij de gemeente aan. Daarnaast blijven we binnen het voor ons aangewezen bouwvlak en blijft de bestemming van ons terrein hetzelfde. Hierom is het vrij reëel dat we de vergunning zullen krijgen.

Op het moment van afwijzing moet je vaak een aanpassing doen om binnen de vergunning te vallen. Dit zullen wij dan doen met onze professionals. Mocht het echt niet lukken om een vergunning te krijgen, dan zijn we het geld voor de aanvraag kwijt
