### ISSUE TITLE
Vraagje over kosten buren

### ISSUE THREAD

**Issue by BaukeBr** [Plan-van-Bouw/ALV_November_2023#37]
Volgens de samenvatting gaat aanbouw zo’n 2,7 miljoen kosten. Welke kosten zitten er allemaal aan verbonden dat uitkoop niet mogelijk zou zijn in plaats van aanbouw? Is deze mogelijkheid al een keer uitgewerkt en kunnen we die nog inzien?

              Dit is inderdaad eerder overwogen en overleg over geweest, echter is dit financieel niet haalbaar

_Originally posted by @IngeMarieke in https://github.com/Plan-van-Bouw/ALV_November_2023/issues/28#issuecomment-1832467028_

**Comment by IngeMarieke** [comment]
Met de buren is afgesproken dat we niet bekend mochten maken hoe veel zij precies voor hun grond wilden hebben. Echter kan ik je wel vertellen dat deze kosten in dezelfde ordegrootte zit en dat het uitkopen van de buren dus even duur tot duurder is dan het uitvoeren van de aanbouw

**Comment by BaukeBr** [comment]
Duidelijk! Dankje
