### ISSUE TITLE
Wat gebeurt er in het geval van vertraagde bestellingen?

### ISSUE THREAD

**Issue by Dux02** [Plan-van-Bouw/ALV_November_2023#38]
Zie bijvoorbeeld te tramlijn op de tu die nu stil ligt? Is er ergens enige wijze van garantie dat als er besteld wordt het er ook daadwerkelijk optijd komt ?

**Comment by IngeMarieke** [comment]
Nee, helaas kan het voorkomen dat producten later geleverd worden. Echter hebben wij al wel geïnformeerd naar de levertermijn van de voor ons belangrijke elementen voor de aanbouw. Omdat deze in sommige gevallen een lange levertijd hebben, hebben wij de planning hierop aangepast omdat het pas reeel is om na de zomer te beginnen met bouw.
