### ISSUE TITLE
Waarom sluiten jullie elk issue zo snel?

### ISSUE THREAD

**Issue by JasperBoogers** [Plan-van-Bouw/ALV_November_2023#39]
Dan kan niemand meer reageren, en mijn vraag is net niet beantwoord...

**Comment by IngeMarieke** [comment]
Hoi! Als je vraag niet is beantwoord kun je een vervolgvraag stellen in de thread, wij zullen hem dan heropenen en beantwoorden! Het idee is dat we hierdoor een duidelijk overzicht hebben van welke vragen nog niet zijn beantwoord. (Maar; dus voor de duidelijkheid: een gesloten vraag kan weer geopend worden)

**Comment by JasperBoogers** [comment]
Dank
