### ISSUE TITLE
Jaarbedrag

### ISSUE THREAD

**Issue by 90zaza** [Plan-van-Bouw/ALV_November_2023#40]
Is er later nog gekeken naar of men deze enquete juist begrepen heeft? In de wandelgangen is gebleken dat veel mensen deze enquête begreep als contributie BOVENOP de besparingen van de vorige enquête, niet in plaats van. Ik denk dat dat het plaatje immens veranderd
 

_Originally posted by @larsdevries6 in https://github.com/Plan-van-Bouw/ALV_November_2023/issues/29#issuecomment-1832476499_

**Comment by larsdevries6** [comment]
Dit is nog niet gedaan maar wel een stap die wij gaan ondernemen. Wij hebben wel ons best gedaan inspraak momenten te houden, alleen was de opkomst zeer laag. Echter zullen wij voor de volgende ALV door behulp van een nieuw inspraakmoment(en) de besparingslijst toetsen aan de wensen van de leden.
