### ISSUE TITLE
Als we na de owee beginnen, kunnen we dan wel een soort van irt draaien?

### ISSUE THREAD

**Issue by Jornvanbeek** [Plan-van-Bouw/ALV_November_2023#41]

**Comment by IngeMarieke** [comment]
Hoi Jorn,

Tijdens de Bouw zullen we creatiever moeten zijn in hoe we onze sociale activiteiten vorm zullen gaan geven. Echter zal roeien altijd mogelijk zijn. Voor de overige activiteiten van de IRT zullen we een alternatieve invulling moeten vinden. Het zal hoe dan ook geen normale IRT zijn, maar we zullen er wel een kunnen houden.
