### ISSUE TITLE
Bezwaartijd

### ISSUE THREAD

**Issue by Tymen249** [Plan-van-Bouw/ALV_November_2023#42]
zit de tijd van bezwaar van bewoners al ingerekend in het plan. Je hebt nml in elke gemeente wel wat van die principiële bezwaarmakers

**Comment by LisevE** [comment]
Ja, wij hebben hier rekening mee gehouden in onze planning. Doordat we niet in juli starten met de aanbouw, maar na de Owee, hebben wij extra speelruimte.
