### ISSUE TITLE
Waarom hebben we precies nu de alv, en niet nadat er meer financiële duidelijkheid is?

### ISSUE THREAD

**Issue by RelatiefPE** [Plan-van-Bouw/ALV_November_2023#43]
als op dit moment nog niets duidelijk is over de haalbaarheid van de lening en de keuze voor het wel of niet aanvragen van de vergunning pas daarna gemaakt wordt, is het dan niet handiger om dan ook de alv te doen zodat de PE leden hierover kunnen stemmen? 

Of is er een reden dat het echt nu moet ivm vertraging op andere vlakken?

**Comment by IngeMarieke** [comment]
Hoi!
Het had gekund, echter kun je maar een keer aankloppen bij de bank. (als je eenmaal wordt afgewezen, mag je niet nog een keer terug komen). Hierom is het voor ons belangrijk dat we met een zo sterk mogelijk verhaal bij de bank aankloppen. Als we dus aan de bank kunnen laten zien dat we draagkracht van de vereniging hebben om dit aan te gaan, is ons verhaal sterker. Hierom hebben we hier voor gekozen

**Comment by RelatiefPE** [comment]
Wordt hierbij dan bedoelt ‘draagvlak voor het ontwerp’ of ‘draagvlak voor de vergunning’?

**Comment by IngeMarieke** [comment]
Beide. We willen graag aan de bank kunnen laten zien dat we draagvlak van de vereniging hebben om dit plan daadwerkelijk uit te gaan voeren. Hierom vragen we nu al van de vereniging of we dit plan mogen uitvoeren, zodat we dat kunnen tonen aan de bank
