### ISSUE TITLE
Lening met lager ledenaantal

### ISSUE THREAD

**Issue by MarnixTijhuis** [Plan-van-Bouw/ALV_November_2023#44]
Beste Kascie/Rva,
Afgelopen jaar waren er 300 uitschrijvingen bij Proteus. Hierdoor ging het aantal leden van 966 naar +- 910. Met een niet beschikbaar gebouw gedurende het meerdere deel van het volgende jaar is de kans aanwezig dat er dit jaar ook een groot aantal uitschrijvingen zal zijn. 

We hebben afgelopen owee al meer mensen ingeloot, maar dit heeft helaas niet geleid tot meer mensen die uiteindelijk lid zijn geworden. Die getallen zijn namelijk: 75: 246
76: 237
77: 238 (met 20 meer mensen )

Waarschijnlijk zakken we volgend jaar naar +- 850 leden. Potentieel zullen veel eerstejaars volgend jaar ook lastiger een plek op de DSR kunnen vinden en minder lang lid blijven, maar dat is iets te ver weg dus dat laat ik even buiten beschouwing. Lang verhaal kort, ons ledenaantal wordt missch een stuk lager dan de afgelopen jaren gewend zijn. Is de jaarlijkse bijdrage dan ook nog houdbaar?

**Comment by larsdevries6** [comment]
Visie vanuit de PvB:
Momenteel rekenen wij in de stukken al met 900 leden. Dit is inderdaad een schatting waarvan we nooit kunnen garanderen dat dit ook zo blijft. Echter hebben wij met betrekking tot de financien meerdere keuzes moeten maken over welk bedrag bij welke besparing passen. Deze kunnen negatief uitvallen, maar ook in ons voordeeel werken. Daarnaast hebben wij voor het bouwjaar rekening gehouden met een bedrag van 75k om dit soort negative gevolgen op te kunnen vangen. Dit is een van de dingen die we dus op kunnen vangen mocht dit nodig zijn

**Comment by hoyte** [comment]
Stel we vallen terug op 750-800leden wat niet onreel is kunnen we dat rond krijgen voor 3-4 jaar? Of worden de kosten voor leden toch nog hooger?

**Comment by Lkeurentjes** [comment]
Dat is lastig om nu te zeggen. Als we eenmaal de lening hebben afgesloten zal het jaarbedrag betaald moeten worden. Het zal dan aan het dan zittende bestuur zijn hoe dat precies wordt opgelost. Het kan inderdaad zijn dat dat dan indirect bij hogere kosten voor de leden terecht komt, maar dit kan ook worden opgelost op andere manieren.

Het aantal leden blijft lastig, maar we houden de koers van de NSRF en KNRB aan en die gaat uit van groei van de roeisport en zelfs als we niet meegroeien is over krimp wel heel lastig om iets te zeggen.

**Comment by wouterhoepman** [comment]
Ik snap dat de roeisport groeit, maar zoals marnix al zei, wij krimpen nu al, laat staan straks. Hier geen helder plan voor hebben en niks uitgewerkt lijkt me een matig idee. Je kunt mij overtuigen om voor de stemmen als hier een oplossing voor wordt gegeven. Anders kan ik alleen tegen stemmen
