### ISSUE TITLE
Uitkomst Bouw ALV maart hoeveel x bedrag?

### ISSUE THREAD

**Issue by Dux02** [Plan-van-Bouw/ALV_November_2023#45]
Als er in de Bouw ALV in maart tegen wordt gestemd staat er 348k plus X in welke orde van grote zit die x?

**Comment by larsdevries6** [comment]
Dit zijn eventuele meerkosten die later door een alv zullen gaan, mocht dat nodig zijn. Maar dat is op dit moment niet duidelijk, dus weten we nog niet of het überhaupt nodig hebben
