### ISSUE TITLE
Hoe gaat de OWee eruit zien als het voorterrein veel kleiner gaat worden? (Zowel organisatorisch als financieel)

### ISSUE THREAD

**Issue by jpoulard** [Plan-van-Bouw/ALV_November_2023#46]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by IngeMarieke** [comment]
De start van de bouw zal na de OWee zijn, dus voor de eerstvolgende maakt het geen verschil.
Voor de OWee's daarna zal de invulling iets anders zijn. Ons voorterrein is inderdaad iets kleiner, maar nog steeds best groot. En ik kan je ook verklappen; toen ik lid werd deden we de OWee-feesten nog op het vlot! Dus ik denk dat we hier wel uitkomen :)

**Comment by jpoulard** [comment]
Ik denk dat de OWee in de afgelopen jaren enorm is veranderd. Het lijkt mij niet verantwoord om zoveel mensen op het vlot te laten. Vorig jaar waren er 2500 mensen op het sportfeest en als we dat niet kunnen faciliteren zullen we niet alleen leden maar ook veel geld mislopen en geld is niet iets waar we te veel van hebben met de bouw.

**Comment by IngeMarieke** [comment]
Het zou kunnen, er is inderdaad iets minder buitenruimte wanneer de aanbouw er staat. Als we meer ruimte willen creeëren kunnen we er voor kiezen om ook het feest deels naar binnen te verplaatsen. Zo hebben we een betere connectie tussen de barzolder en het vlot. Daarnaast kunnen we ook de deuren uit de nieuwe commissiekamers naar het vlot open zetten.

**Comment by jpoulard** [comment]
Helaas zijn de commissiekamers allemaal druk bezet tijdens de owee, daar is zelfs al een tekort aan. Om het feest naar binnen te verplaatsen krijgen we ook problemen met licht en geluid, barvoorzieningen en overzicht voor de organisatie. Wel bedankt voor je antwoorden!
