### ISSUE TITLE
Wat betekend een positieve uitkomst van het gesprek met de bank? In de begroting staat 4,5% rente. Betekend dit dat over alle rente daarboven weer een nieuwe ALV moet komen?

### ISSUE THREAD

**Issue by markfromthemountain** [Plan-van-Bouw/ALV_November_2023#48]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by IngeMarieke** [comment]
Heeey,

Als het jaarbedrag significant veranderd komen we wel terug naar de ALV, voor kleine aanpassingen rondom keuzes zullen we met de grote spelers meeting overwegen of we door mogen naar de volgende stap. Of uiteindelijk de volgende lening wordt goedgekeurd is dan een keuze van de volgende ALV.

**Comment by markfromthemountain** [comment]
Denk dat je deze vraag al aan kan voelen komen. Maar wat is significant? Want een half procent rente maakt denk ik op een totaal bedrag vrij veel uit.

**Comment by larsdevries6** [comment]
Wij rekenen nu voor de banklening met een liniear aflosbare lening van 15 jaar met een 4.5 % rentepercentage. Dit is gebruikt om tot een jaarbedrag te komen. Wij zullen aan de hand van de gesprekken met de bank een concreet aanbod krijgen. Zo zouden we een linieare maar ook annuitaire lening kunnen krijgen, in de aflossingsduur nog onbekend evenals het rentepercentage. Hierdoor kan het bedrag nog veranderen. Dit verwachten wij op de volgende ALV (maart 2024) te presenteren. Mocht er onverhoopt een grote verandering zijn zal dit altijd langs de ALV moeten gaan
