### ISSUE TITLE
Hoeveel toegang is er tot de vereniging volgend jaar?

### ISSUE THREAD

**Issue by BaukeBr** [Plan-van-Bouw/ALV_November_2023#49]
Als er aan de Beuk volgend jaar 42 weken lang gewerkt wordt en dus deels gesloten is, wat voor toegang hebben leden dan na de zomer? Kan er nog veel geroeid en geborreld worden en zo ja wat wordt dan wel gesloten?

**Comment by IngeMarieke** [comment]
In de kern zijn wij een roeivereniging. Er zal dus altijd geroeid kunnen worden.

Daarnaast vinden wij onze sociale activiteiten en borrels als vereniging natuurlijk ook belangrijk. Dit zal tijdens de bouw een jaar lang wel natuurlijk minder nice zijn. We zullen naar alternatieve oplossingen moeten gaan zoeken; denk aan externe locaties, of huur van bijvoorbeeld noodlokalen. Er is hier geld voor begroot & in het TO zal dit verder worden uitgewerkt. Goede ideeen hierover zijn natuurlijk ook altijd welkom!

**Comment by Semv6** [comment]
Leuk idee dit, maar wie gaan die externe borrels organiseren? Als beheer hebben we nog niks hierover gehoord. Zomaar ergens anders borrelen is niet zo makkelijk als je denkt

**Comment by IngeMarieke** [comment]
Hoi!
Een externe borrel was een van de mogelijke voorbeelden. Zoals gezegd zullen we dit in de volgende (TO) fase verder uitwerken. Hoe dan ook zal borrelen een jaar lang best behelpen zijn.

 Het lijkt mij zeker nice als het Beheer zou willen helpen om hier iets in te organiseren en het lijkt mij ook goed om het hier in de volgende fase over te hebben

**Comment by DaniqueBuchner** [comment]
Hola! Ik wil kort even inhaken op Sem. Tijdens de beleids-alv heb ik over het beleid en/tijdens de bouw gepresenteerd en het gehad over op externe locatie borrelen, er zijn toen ook vragen gesteld door het beheer en er is toen kort over gepraat over borrelen en feesten als de club dicht is
