### ISSUE TITLE
Waar gaan we deze alv precies over stemmen?

### ISSUE THREAD

**Issue by Noudvb** [Plan-van-Bouw/ALV_November_2023#5]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by DaniqueBuchner** [comment]
Deze ALV van 29 november zullen we stemmen over het afronden van de Definitieve Ontwerpfase (DO) en het starten van de Technisch Ontwerp- en Voorbereidingsfase (TO). _In deze fase gaan we de omgevingsvergunning bij de gemeente en de financiering bij de bank aanvragen. Beide zijn dure processen die veel tijd kosten maar die belangrijk zijn om nu te ondernemen. Wel is het belangrijk om te weten dat we nu nog niet voor een akkoord stemmen over de aannemersbegroting of de definitieve lening, dit volgt in een latere ALV. Wel wordt het steeds lastiger en duurder om een stap terug te gaan in het proces omdat de investering en commitment naar de andere partijen vanuit de vereniging steeds groter wordt._ 

**Voor stemmen betekent dus:**
- Het goedkeuren van de Definitieve Ontwerpfase,
- Het DO uitwerken naar TO niveau, met de volgende kosten als gevolg:
     - €69.000 voor de omgevingsvergunning
     - maximaal €130.000 voor de diensten
     - €2.500 voor de commissiekosten
- Een financieringsaanvraag doen, en daarvoor in gesprek gaan bij de bank.

We stemmen deze ALV dus **niet** over:
- Het ondertekenen van de aannemersovereenkomst
- Het afnemen van de lening
- De opbouw van het jaarbedrag om de lening terug te betalen (contributieverhoging etc.)
- De diensten in de uitvoeringsfase
