### ISSUE TITLE
Waarom wordt het huidige bestuurshok niet bij de barzolder toegevoegd?

### ISSUE THREAD

**Issue by Semv6** [Plan-van-Bouw/ALV_November_2023#50]
In het ontwerp word de barzolder vergroot met een paar centimeter bij de deur. Die zijn praktisch nutteloos, bij een feest wil niemand daar staan. Dus waarom niet het huidige bestuurshok erbij?

**Comment by LisevE** [comment]
De barzolder wordt wel groter (er komt 24 m2 bij), het huidige bestuurshok wordt grotendeels loopruimte en de deur van de barzolder wordt dubbel zo breed. Als je het precies op de plattegrond wil zien, moet je even bij ons langslopen dan laten wij je het zien.
