### ISSUE TITLE
Is het mogelijk om het balkon groter te maken door de buitenrand evenredig te maken aan de schuine hoek van de beuk of past dit niet met de dijk?

### ISSUE THREAD

**Issue by Nieksebas** [Plan-van-Bouw/ALV_November_2023#51]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by LisevE** [comment]
Je hebt gelijk, dit past inderdaad niet. Omdat ons vlot onderdeel is van een dijk mogen we niet te ver naar het water bouwen, ons bouwvlak eindigt op de lijn van de loodsgevel.
