### ISSUE TITLE
Is de vandalisme test van het kalkhennep door lompe Proteërs al uitgevoerd?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#52]

**Comment by wouterhoepman** [comment]
Ik hou mezelf beschikbaar

**Comment by IngeMarieke** [comment]
Het is een hard bouwmateriaal, wat alleen beschadigd als je met een hamer/beitel in ramt. Daarnaast hebben we maatregelen genomen om op kwetsbare plekken platen of hoekprofielen te plaatsen.

**Comment by IngeMarieke** [comment]
> beschikbaar

Voor het stampen? ⭐

**Comment by wbakkeren** [comment]
Maar ook als er bier overheen gaat bijvoorbeeld? Dit was al een topic op de vorige alv namelijk

**Comment by wbakkeren** [comment]
Ik heb (helaas) op deze vereniging al vaker dingen stuk zien gaan waarvan ik dacht dat ze echt niet stuk konden.

**Comment by IngeMarieke** [comment]
> Maar ook als er bier overheen gaat bijvoorbeeld? Dit was al een topic op de vorige alv namelijk

ja, verder kunnen we het kalkhennep altijd nog op meer plekken inpakken, mochten de inschattingen niet juist zijn
