### ISSUE TITLE
Proteus leningen

### ISSUE THREAD

**Issue by Koramund** [Plan-van-Bouw/ALV_November_2023#53]
Zal proteus nog steeds kunnen fungeren als bank voor comissies, vloten en leden? De matcie en magnum schieten nu als eerste te binnen die geld nodig hadden van proteus om dat later terug te betalen. Als we eenmaal alles in de bouw hebben zitten voor 15 jaar, kunnen wij dan nog hetgene financieren wat proteus leuk voor proteus maakt.

**Comment by fcluistra** [comment]
En blijft er nog geld over voor het opzetten van 'projecten' als de Iris of de LVC die Proteus toch echt wel op de kaart zetten en zichzelf terugverdienen, maar wel een investeringsinjectie nodig hebben?

**Comment by JasperBoogers** [comment]
Volgens de stukken is de minimale liquiditeit ten alle tijden 120k, daar kan je wel een injectie van doen toch?

**Comment by larsdevries6** [comment]
Er wordt in de stukken altijd gerekend met een minimale balans van proteus. Deze zal altijd groter zijn dan 119k. Dit bedrag kan gebruikt worden voor proteus om dingen voor te schieten. Daarnaast willen we wedstrijden gelden, maar mogelijk ook trainingskampen en contributie eerder (vooraf) gaan innen.
