### ISSUE TITLE
Invulling oude keuken/beheerhok

### ISSUE THREAD

**Issue by Echtchef** [Plan-van-Bouw/ALV_November_2023#54]
Ik begreep dat alleen details nog aangepast kunnen worden. Ook las ik in de stukken dat de invulling van de oude keuken/beheerhok nog niet vastgesteld is.

Ook heb ik vernomen dat er de intentie is om het beheerhok in grootte te verdubbelen. Kunnen jullie hier iets meer toelichting over geven?

**Comment by RobinGeijsel** [comment]
Hoi, naast de details wordt ook nog gewerkt aan de installaties. Op dit moment is het nog niet helemaal duidelijk hoeveel van de ruimte rond de nieuwe keuken, bijkeuken en het beheerhok nodig gaat zijn voor installaties. Als uitzondering op de rest van het gebouw zal hier dus meer aangepast moeten worden in het TO. Wanneer dat duidelijk is hoeveel ruimte de installaties innemen zal in overleg met de betrokken commissies een indeling gemaakt worden voor deze functies. Er is ruim voldoende ruimte voor alle functies en het gaan voornamelijk over meubels en apparatuur, daarom hebben wij er vertrouwen in dat dit in de volgende fase goed uitgewerkt kan worden.

**Comment by RobinGeijsel** [comment]
.

**Comment by RobinGeijsel** [comment]
Dit gaat om erg lichte muren die geen dragende functie hebben en zelf geplaatst\verplaatst kunnen worden. Daarom is het mogelijk om te wachten tot we meer kennis hebben over installaties.
