### ISSUE TITLE
Krijgen we nog een mogelijkheid om open over de vragen en dergelijke te discussiëren? 

### ISSUE THREAD

**Issue by fcluistra** [Plan-van-Bouw/ALV_November_2023#55]
Ik vind het op een ALV altijd wel nice om meningen van leden te horen en vervolgvragen met discussie. Vaak komen daar belangrijke punten aan het licht en wordt het onderwerp ook vanaf andere kanten belicht dan alleen die van de presentator.

**Comment by MWMKievit** [comment]
Ik sluit me hier graag bij aan

**Comment by hoyte** [comment]
Dit is gewoon een recht van de alv voor een stemming. Het lijkt me dan ook dat dit kan plaatsvinden voor de stemming

**Comment by RelatiefPE** [comment]
Eens

**Comment by Lkeurentjes** [comment]
Heeey fleur & Mark,

Adhv de vorige Bouw ALV hebben we besloten om dit niet te doen, er worden makkelijk veel onwaarheden etc. heen en weer gegooid en dat is niet super handig. Ook kunnen we jullie vragen op deze manier veel uitgebreider beantwoorden. We snappen dat dit ook niet alles is, maar hebben hier bewust voor gekozen en dit meermaals aangegeven. Je kan in de Github wel reageren en met elkaars meningen mee lezen en we proberen met de pauzes ook ruimte te geven om met ons en met elkaar in discussie te gaan.

**Comment by Ziekekip** [comment]
Ik vind dit heel gevaarlijk, hiermee maak je eventuele discussies die jullie niet leuk vinden monddood en kan je dus niet als lid de rest van de Alv op bepaalde dingen wijzen.

**Comment by Tymen249** [comment]
Iets wat helaas (expres of per ongeluk) ook bij eerdere alv's gebeurde

**Comment by fcluistra** [comment]
Dat vind ik echt heel vreemd... Ik snap dat er tijdens de presentaties geen ruimte is voor dit soort discussies omdat alles dan echt veel te lang zou duren, maar ik zou het niet onlogisch vinden als er voor de stemming een mogelijkheid is tot 'inspraak' van de leden tov van alle aanwezigen. Want niet iedereen leest de Github en bovendien vind ik het best lastig om zowel de Github in de gaten te houden, als iets van de presentatie mee te krijgen. Terwijl je een openlijke discussie sowieso meekrijgt en dus mee kan nemen in je overwegingen.

**Comment by fcluistra** [comment]
En stel er worden onwaarheden verkondigd, kan de PVB natuurlijk altijd nog tussen de discussie springen en de onwaarheden verbeteren. Net zoals in een debat kan er gewoon orde geroepen worden en dienen mensen naar elkaar te luisteren.

**Comment by wouterhoepman** [comment]
Het voelt alsof dit er gewoon doorheen gedrukt wordt. Sjaarspunten voor de sjaarsladder worden uitgedeeld voor aanwezigheid van onwetende eerstejaars, eenzijdige verhalen worden gehouden op het podium  Er wordt je een schuldgevoel aangepraat als je tegen stemt. Waar is de discussie, waar is het debat, dit kan niet de bedoeling zijn. We staan op het punt 3 miljoen uit te geven, dit is niet iets dat er zonder debat doorheen mag.

**Comment by Lkeurentjes** [comment]
We hebben hier samen met het bestuur een conlusie over gemaakt. We zullen het ontwerp vragen moment & het financiele vragen moment opdzelfde manier doen als de vorige. Daarna zullen we nog een samenvatting presenteren, daarna geven we nog een moment voor discussie. We zullen dit zo ook na de pauze verkondiggen.


Het is hier de bedoeling om kritische vragen en daarop in te haken, en niet een plek voor persoonlijke meningen. Het is niet de bedoeling om er iets doorheen te drukken. Het gaat erom dat we niet tot 2 uur snachts weer hier zitten. We zien wel iedereens persoonlijke mening graag tegemoet op het stembilljet!

**Comment by JasperBoogers** [comment]
Wat nou als er aan het einde van alle presentaties een discussie moment met tijdslimiet komt? Kan iedereen dan zn ei kwijt

**Comment by Lkeurentjes** [comment]
@JasperBoogers yesh dat is dus nu de bedoeling, na de samenvatting!
