### ISSUE TITLE
Hoe worden zaken als hygiëne aangepakt als veel van de ruimtes vergelijkbaar blijven?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#56]
Kleedkamers veranderen wel in commissiekamers bijvoorbeeld, maar aan de muren enzo verandert er weinig toch?

**Comment by LisevE** [comment]
De bestaande muren, die blijven staan, zullen een onderhoudsbeurt krijgen en aan onze eisen van de nieuwe functie van de ruimte moeten voldoen. Denk aan, gaten dichten, schoonmaak, verven, etc. Sowieso komt er in elke ruimte een nieuwe vloer dus op muizenhoogte wordt er veel verbeterd.
