### ISSUE TITLE
Is het mogelijk bij een "nee" onderdelen van de plannen mee te nemen naar een eventuele doorstart?

### ISSUE THREAD

**Issue by NinoGB** [Plan-van-Bouw/ALV_November_2023#57]
Zouden we later bijvoorbeeld alleen de aanbouw aan de vlot zijde kunnen neerzetten?

**Comment by Lkeurentjes** [comment]
Er moet dan nogsteeds wel daar een TO overheen gaan en een keuze worden gemaakt. Dus ja het zou eventueel wel kunnen maar  het is tijdstechnisch best ingewikkeld en we zullen er snel keuzes over maken. Dus ja het zou wel kunnen, maar persoonlijk acht ik de kans dat we dat (snel) gaan doen vrij klein.
