### ISSUE TITLE
Barzolder maat

### ISSUE THREAD

**Issue by Tymen249** [Plan-van-Bouw/ALV_November_2023#58]
Is bij die 20m^2 extra op de barzolder ook gekeken naar extra benodigde loopruimte om op de bar te komen, dit zou namelijk de 20m^2 fiks compenseren/verlagen

**Comment by thirzave** [comment]
De piano-hoek wordt groter en wordt bij de barzolder getrokken. Dit lijkt misschien veel loopruimte maar we zien dat er nu al gechillt wordt en als deze hoek groter wordt zal dit meer gebeuren. Ook komt de deur verder richting de trap dus je staat er warm. Beantwoordt dit je vraag?
