### ISSUE TITLE
Is het nog mogelijk om het balkon deels overdekt te maken?

### ISSUE THREAD

**Issue by RelatiefPE** [Plan-van-Bouw/ALV_November_2023#59]
Spullen/stoelen die tijdelijk op het balkon worden gezet zullen dan beter beschermd zijn en minder snel aftakelen

**Comment by LisevE** [comment]
Dit zal daglicht op de barzolder tegenhouden, dit is wat we juist niet willen, aangezien we er juist met de aanbouw voor willen zorgen dat er meer licht de barzolder komt.
