### ISSUE TITLE
Hoe werk dat bouwteam nou precies?

### ISSUE THREAD

**Issue by PvBouw** [Plan-van-Bouw/ALV_November_2023#6]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by DaniqueBuchner** [comment]
Een bouwteam is een samenwerkingsvorm waarin, ondanks de naam, vooral veel ontworpen wordt. In een bouwteam zitten alle belangrijke partijen al erg vroeg in het ontwerpproces samen om tafel, in tegenstelling tot 'traditionelere' samenwerkingsvormen waarin eerst een architect een ontwerp maakt, en dan het stokje in één keer doorgeeft aan de aannemer. 
Een groot voordeel van een bouwteam is dus dat de architect tijdens het ontwerpen al in gesprek is met (in ons geval) de aannemer, de constructeur en de bouwfysisch adviseurs, waardoor al deze belangrijke aspecten vroegtijdig in het ontwerp kunnen worden opgenomen.
