### ISSUE TITLE
Hoe wordt de kans ingeschat dat er na de omgevingsvergunningsaanvraag nog aanpassingen gedaan moeten worden en/of naar aanleiding hiervan er een extra ALV komt?

### ISSUE THREAD

**Issue by Kjalbers** [Plan-van-Bouw/ALV_November_2023#60]
Ik vraag me vooral af in hoeverre er al met de gemeente (of welke instantie de omgevingsvergunning vergeeft) overlegd kan worden hoe realistisch een positieve uitkomst is. Eventuele op- of aanmerkingen zou je dan in een eerder stadium al kunnen verwerken in het TO.

**Comment by IngeMarieke** [comment]
Hoi Kjell!

Voordat we de vergunningsaanvraag zullen we eerst een vooroverleg met de gemeente hebben. Hierdoor zullen we dus hopelijk alvast een duidelijk beeld van de Gemeente hebben wat de elementen zijn waar zij mogelijk moeite mee hebben uit ons plan. Inderdaad zouden we die feedback al mee kunnen nemen!
