### ISSUE TITLE
Ventilatie keuken

### ISSUE THREAD

**Issue by Tymen249** [Plan-van-Bouw/ALV_November_2023#61]
De keuken kan op dit moment alle lucht uit de barzolder trekken, om dit in de toekomst te voorkomen, komt er ook een vorm van ventilatie in de keuken?

**Comment by RobinGeijsel** [comment]
In het nieuwe ontwerp zal er een grotere afstand zitten tussen de keuken afzuiging en de barzolder. Daarnaast zullen hier meer deuren tussen komen. Dit zal dit probleem aanzienlijk verminderen. Echter zal door kieren kan nog altijd wat lucht kunnen wegtrekken. Als dit je vraag niet beantwoordt kun je volgende pauze even langlopen om het met een plattegrond erbij te bespreken.
