### ISSUE TITLE
Ecologisch vs goedkoop bouwen

### ISSUE THREAD

**Issue by Koramund** [Plan-van-Bouw/ALV_November_2023#64]
Als we dat maatwerk dak (kunnen) schrappen hoe ziet het financiële plaatje er dan uit? Of als we minder focussen op duurzaam bouwen (ecologisch) maar puur isolerend bouwen hoeveel goedkoper komen we dan uit?

**Comment by RobinGeijsel** [comment]
Het dak isoleren is nodig om een comfortabel klimaat is het gebouw te krijgen. Wanneer dit niet gedaan wordt zal er gecompenseerd moeten worden in installaties en energiekosten. Daarom geeft het bedrag wat we zouden besparen in bouwkosten niet het hele verhaal.

**Comment by Koramund** [comment]
En de 2e vraag, stel we focussen niet op ecologisch materiaal maar puur op goedkoop isolerend bouwen?

**Comment by Koramund** [comment]
@PvBouw @RobinGeijsel
