### ISSUE TITLE
Beheer winst

### ISSUE THREAD

**Issue by Koramund** [Plan-van-Bouw/ALV_November_2023#65]
Gaan de berekeningen er ook vanuit dat dat eerste jaar het beheer dus 0 winst draait aangezien we dicht zijn?

**Comment by larsdevries6** [comment]
Wij houden er momenteel rekening mee dat het beheer een zeer sterk verminderde afdracht gaat draaien in het bouwjaar. Echter streven wij er ook naar om de bar gedurende de bouw deels open te kunnen houden of dat er op het vlot geborreld kan worden.

**Comment by wbakkeren** [comment]
Ik ben benieuwd hoe het beheer hierover nadenkt

**Comment by Echtchef** [comment]
T beheer heeft dit niet uitgerekend, omdat we hier te weinig informatie voor hebben.

Mijn persoonlijke inschatting zou zijn dat 't beheer in een bouwjaar zoals dat geschetst is tijdens de presentatie(s) en in de stukken niet positief kan draaien.
Pennie beheer 27

**Comment by wbakkeren** [comment]
Enige inschatting / ballpark wat dat betekent qua staffel en financiële gevolgen?

**Comment by Echtchef** [comment]
Ik weet niet of ik in de positie ben om dat mede te delen aan de ALV. Wellicht kan de pvb/kascie hier uitsluitsel over geven.

**Comment by wbakkeren** [comment]
In dat geval, kan hier een labeltje ‘vragen aan kascie’ aan gehangen worden @pbv?
