### ISSUE TITLE
Duurzaamheidseisen isolatie bouw niet relevant voor Beuk?

### ISSUE THREAD

**Issue by teundomburg** [Plan-van-Bouw/ALV_November_2023#66]
Ik dacht dat we met het verbouwen het hele gebouw up to standard moesten krijgen, maar de staande buitenmuren van de Beuk die we houden hoeft niks nieuws aan qua isolatie?

**Comment by LisevE** [comment]
Er is gekeken door onze professionals, welke delen van onze bestaande beuk beter geïsoleerd moeten worden. De dichte delen van de buitenmuren voldoen goed genoeg en zijn een extra investering niet waard. De open delen, waaronder de nieuwe erkers voor meer daglicht, krijgen wel een betere isolatiewaarde dan de huidige ramen.
