### ISSUE TITLE
Hoe heropen je een issue?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#67]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by 90zaza** [comment]
Heb idd het idee dat wij dat niet kunnen

**Comment by IngeMarieke** [comment]
Whoeps, dat zei ik verkeerd. Dat kunnen alleen wijzelf. Echter krijgen wij wel een melding als er opnieuw wordt gereageerd en zullen wij hem dan heropenen!
