### ISSUE TITLE
Hoeveel posters kan je printen voor €2500?

### ISSUE THREAD

**Issue by Nieksebas** [Plan-van-Bouw/ALV_November_2023#68]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by IngeMarieke** [comment]
Hoi, geen idee. Misschien kun je dit zelf opzoeken?

**Comment by larsdevries6** [comment]
Onder de overige kosten vallen poster, reiskosten, materialen voor de ALV zoals de beemer, maar ook de uitgaven die wij moeten maken aan de wervingsacties.

**Comment by Nieksebas** [comment]
Zouden die kosten verder uitgesplitst kunnen worden?
