### ISSUE TITLE
Tot welk rentepercentage zijn de jaarkostem doorgerekend?

### ISSUE THREAD

**Issue by Nieksebas** [Plan-van-Bouw/ALV_November_2023#70]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by Lkeurentjes** [comment]
bedoel je het rentepercentage van de lening? of een ander percetage?

**Comment by Nieksebas** [comment]
Van de lening ja, 4.5% lijkt erg optimistisch

**Comment by Lkeurentjes** [comment]
Voor een zakelijke lening was dit een logische rente percentage volgens de financiele adviseur en volgens hem realistisch. Haha ik weet niet zeker of je met optimistisch hoog of laag bedoeld, maar we hebben het in ieder geval niet zelf uit onze duim gezogen! Beantwoord dat je vraag?

**Comment by Lkeurentjes** [comment]
Ook zijn er nog mogelijkheden tot duurzaamheids lenen of deels duurzaamheids lenen, bijvoorbeeld voor de instalaties een losse " ddurzaamheids"  lening, dit kan ook ook rentepercentage drukken, want hiervoor gelden vaak 1% leningen
