### ISSUE TITLE
Aegir heeft ook vloerverwarming wordt alleen gebruikt tijdens evenementen zal dat anders zijn op pe?

### ISSUE THREAD

**Issue by Dux02** [Plan-van-Bouw/ALV_November_2023#71]
Op Aegir wordt alleen de vloerverwarming aangezet voor grote evenementen zoals de hel anders niet. Hoe reëel is het dat de vaste last van bv vloerverwarming te hoog is en daardoor niet aan zal staan? Met als resultaat dat we het misschien beter niet aan kunnen leggen... En feite is er gekeken naar welke installaties wij willen installeren en welke andere verenigingen die nu ook beschikken en hoeveel ze ook daadwerkelijk gebruikt worden?

**Comment by Lkeurentjes** [comment]
Yes we zijn daar inderdaad naar aan het kijken. Het is vooral kosten en baten afwegen, deels op basis van comfort en deels op basis van energie rekening. Maar we zullen niet zomer een duur systeem aanschraffen wat nooit gebouwd wordt, we zijn opzoek naar de Opel, niet de mercedes

**Comment by JasperBoogers** [comment]
Maakt Aegir ook nog gebruik van andere bronnen van verwarming? Over het algemeen is vloerverwarming een stuk efficiënter dan convectie, en de enige vaste last is de aanschaf?
Je tweede vraag vind ik overigens een heel goed punt

**Comment by Lkeurentjes** [comment]
We hebben nog niet specifiek eagir gesproken, knorren hebben toch vaak makkelijker contact met andere knorren, maar we zullen er even achteraan gaan!
