### ISSUE TITLE
Klopt het dat die vergunning die nodig is om aan de balkon kant te bouwen voor kade veiligheid etc niet in meegenomen in dit overzicht? Hoeveel zal dit gaan kosten?

### ISSUE THREAD

**Issue by RelatiefPE** [Plan-van-Bouw/ALV_November_2023#72]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by IngeMarieke** [comment]
Sorry, ik begrijp je vraag niet. Welke vergunning bedoel je?

**Comment by RelatiefPE** [comment]
In de stukken stond dat omdat wij deel zijn van de dijk, we dus ook een vergunning nodig hebben om hier te bouwen.

**Comment by DaniqueBuchner** [comment]
Die vergunning is een onderdeel van de omgevingsvergunning

**Comment by Lkeurentjes** [comment]
We doen deze tegelijkertijd aanvragen en we hebben de kosten opgeteld bij de totale omgevingsvergunning! Deze is gelukkig een stukje goedkoper!

**Comment by RelatiefPE** [comment]
Dus de omgevings vergunning is deel van de waterschaps vergunning? En deze zullen dus als geheel worden getoets? 

Beïnvloed dit dan ook de kansen op het goedkeuren van beide vergunningen?

**Comment by IngeMarieke** [comment]
de kosten voor de waterschapsvergunning zijn opgenomen in de post voor de omgevingsvergunning. Inderdaad moeten beide vergunningen goedgekeurd worden
