### ISSUE TITLE
Spaarplannen

### ISSUE THREAD

**Issue by Tymen249** [Plan-van-Bouw/ALV_November_2023#73]
Bij het gebruik van liquide middelen uit de spaarplannen wordt aangegeven dat er nog wel geld over blijft. Maar is dit een beperkt bedrag, of kunnen commissies nog steeds grote en/of onverwacht uitgaven doen (bijv. De bixy als de oven overlijdt)

**Comment by larsdevries6** [comment]
Omdat wij alle spaarplannen samengevoegd hebben worden de risico's ook verdeeld. Hierdoor kunnen de commisies gezamelijk/proteus dit soort gevallen opvangen.
