### ISSUE TITLE
Obligaties

### ISSUE THREAD

**Issue by 90zaza** [Plan-van-Bouw/ALV_November_2023#74]
Hoe gaat het met die obligaties? Zijn de inkomsten in lijn met de verwachte inkomsten?

**Comment by MarnixTijhuis** [comment]
Leuke gebruikersnaam @90zaza

**Comment by larsdevries6** [comment]
We proberen de obligaties zo veel mogelijk onder de aandacht te bregen. Inmiddels hebben we al voor 26k aan obligaties staan, maar hoe meer hoe beter.

**Comment by Echtchef** [comment]
Maar komt dit overeen met de verwachtingen?
