### ISSUE TITLE
Is de Lening Proteus een echte lening of een mutatie?

### ISSUE THREAD

**Issue by Dux02** [Plan-van-Bouw/ALV_November_2023#75]
Er wordt als het waren intern geleend binnen de organisatie betekend dit ook dat we rente betalen over die lening of is het een mutatie binnen de voorziening?

**Comment by larsdevries6** [comment]
Nee, het geld wat we uit spaarplannen van onszelf lenen is al van ons dus hoeven we geen rente over te betalen
