### ISSUE TITLE
Hoe grote tegenvallers kunnen deze plannen nekken?

### ISSUE THREAD

**Issue by Jornvanbeek** [Plan-van-Bouw/ALV_November_2023#76]
De aanbouw ging toendertijd niet door vanwege een flinke financiele tegenvaller. Wat voor ordegrootte tegenvaller denken jullie te kunnen hebben waarbij we alsnog kunnen gaan bouwen? (Een grove schatting, naast het onvoorzien potje). Daarbij de vraag voor het jaarbedrag en de totale kosten.

**Comment by Lkeurentjes** [comment]
De vorige finaciele tegenvaller had deels ook te maken met als we dan doorgingen het wegvallen van onze hoofdsponsor, de TU delft. Het is nu lastig om te zeggen waar we precies wel of niet mee kunnen nemen. We hebben iig nog 1 ton onvoorzien begroot en ook de spaarplannen heel streng voor onszelf naar beneden afgerond. Dus er zit zeker wat marge in, maar wat wel en niet is lastig om in te schatten
