### ISSUE TITLE
Wanneer worden de spaarplannen weer vanouds?

### ISSUE THREAD

**Issue by Semv6** [Plan-van-Bouw/ALV_November_2023#77]

**Comment by Lkeurentjes** [comment]
Ik snap niet helemaal wat je bedoeld met deze vraag? Inprincipe veranderd er niks aan de spaarplannen zelf, we gebruiken alleen het "stilstaande geld".

**Comment by Lkeurentjes** [comment]
De spaarplannen zelf zullen gewoon kunnen worden uitgevoerd. We zullen 3 a 4 jaar na het einde de lening al dit stilstaande geld terug hebben gezet op de bank hebben gezet, waar & indien gewenst
