### ISSUE TITLE
Waar komt de fietsenstalling etc.?

### ISSUE THREAD

**Issue by Communikati** [Plan-van-Bouw/ALV_November_2023#78]
Ik vroeg me af wat het idee is voor het stallen van fietsen en auto's in het nieuwe plan die op dit moment al een groot deel van het voorterrein in beslag nemen. In de nieuwe situatie is het voorterrein nog kleiner dus zou de ruimte nog meer beperkt worden.

**Comment by thirzave** [comment]
Er is een globale indeling maar er zal zeker voldoende ruimte zij om de fietsen te stallen op het voorterrein.
