### ISSUE TITLE
Wat zijn voorspellingen voor het ledenaantal nadat de verbouwing is gedaan?

### ISSUE THREAD

**Issue by Hannootje** [Plan-van-Bouw/ALV_November_2023#79]
Gaat de vereniging door de verbouwing een groter aantal leden kunnen aantrekken en huizen, als die eenmaal is gedaan. Zodat de schulden die we nu opbouwen terugbetaald kunnen worden met een niet al te grote invloed op de contrubutie (op lange termijn), en of toekomstige onverwachtse kosten dan opgevangen kunnen worden.

**Comment by larsdevries6** [comment]
Ja het zou kunnen dat we meer leden aan nemen, de vereniging heeft wel al is de wens uitgesproken om niet heel veel te groeien, dus we zien dit meer als een beslissing die tzt heroverwogen moet worden.

**Comment by Jornvanbeek** [comment]
Is het niet zo dat we eigenlijk al een beetje tegen het maximum aan zitten wat betreft mensen uitloten? Stel we hebben 500 inschrijvingen maar vervolgens komen er 200 toch niet opdagen dan kun je je ledenstop op 350 zetten, maar dan komen er maar 300. Dus misschien meer een vraag aan bestuur/peik/lotingscommissie!
