### ISSUE TITLE
Hoelang gaat de bouw ongeveer duren?

### ISSUE THREAD

**Issue by Lkeurentjes** [Plan-van-Bouw/ALV_November_2023#8]
En hoe gaan we dat overleven als vereniging?

**Comment by Lkeurentjes** [comment]
Op dit moment staat de planning op 42 weken bij de aannemer. Tel je hier nog een kerstvakantie, wat slecht weer weken, een bouwvak en een uitloop van een maand bij op. Dan kom je uit op circa 52 weken. Reken er dus op dat het gebouw ongeveer een jaar verminderd of zelfs on bruikbaar zal zijn.

**Comment by MarnixTijhuis** [comment]
Is het mogelijk om meer context te geven over het verminderd verbruik of onbruikbaar gebouw?

**Comment by Lkeurentjes** [comment]
Ja en nee. De precieze mogelijkheden rondom het gebruik zullen pas duidelijk worden na een uitgebreide bouwplanning gebaseerd op alle leverancier, dat is echt iets wat in het TO ontwikkeld wordt. Wel weten we al dat het verzekeringstechnisch best ingewikkeld is om gebruik te maken van een gebouw wat deels verbouwd wordt, dus we zijn ook een klein beetje afhankelijk van de verzekering (en de mogelijke meerkosten) hoever we het kunnen oprekken. Wel is de ambitie om de beuk zoveel mogelijk bruikbaar te houden zolang dat kan, welke maanden dat precies wel en niet is is nu lastig. Wel zijn we al bezig geweest met kijken naar het huren van bouwcontainers/tijdelijke klaslokalen voor bijvoorbeeld tijdelijke kleedkamer, een bestuurshok en/of een bar (+ terras), we hebben hier ook al geld voor begroot in het potje "kosten tijdens de bouw". 

De kans zit er dik in dat het jaar er niet helemaal zo uit zal zien als we gewend zijn, maar met een goeie voorbereiding en een hoop ervaring door corona, gaan we er toch iets moois van maken. We zullen iig ter alle tijden open blijven voor roeien, de rest zullen we zo goed mogelijk in alternatieve vormen proberen te faciliteren als het niet helemaal kan in onze beuk.

**Comment by MarnixTijhuis** [comment]
Oke dat is een stuk duidelijker. Snap dat het nu ook lastig inschatten is
