### ISSUE TITLE
Zou er voor de zwevende kiezer in 1 minuut samengevat kunnen worden waarom we "ja" of "nee" zouden moeten stemmen?

### ISSUE THREAD

**Issue by NinoGB** [Plan-van-Bouw/ALV_November_2023#80]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by larsdevries6** [comment]
Er volgt nog een conclusie waarin het allemaal samengevat wordt, daarnaast mag je nog vragen stellen aan ons en krijg je voordat je je stem indien nog tijd om hierover na te denken
