### ISSUE TITLE
Ouders overtuigen

### ISSUE THREAD

**Issue by Koramund** [Plan-van-Bouw/ALV_November_2023#81]
Ik snap niks van obligaties en probeer mijn ouders te overtuigen. Waarom zouden mijn ouders, los dat ze van mij houden, deze obligatie willen aannemen? Voordelen? Nadelen? Risicos?

**Comment by Lkeurentjes** [comment]
Heel kort samengevat:
- Je ouders lenen geld aan Proteus
- Hiervan krijgen ze elk jaar (12 jaar lang) een bedrag terug. 
- Daarnaast zit er een periodieke schenking bij wat betekend dat ze elk jaar geld terug geven aan Proteus
- Indien je ouders belasting betalen over de inkomsten kunnen ze de belasting over de periodieke schenking terug vragen aan de belastingdienst
- Onder aan de streep levert dit een rendement op van 3.3 % per jaar 
Mocht dit niet duidelijk zijn kan je een mailtje naar de Werving van bouw sturen voor meer uitleg
