### ISSUE TITLE
Komt er een groter LoCo hok als we zo veel zelf gaan klussen?

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#84]
zet de vraag in de Titel & geef hier indien nodig een uitleg

**Comment by larsdevries6** [comment]
Na de bouw, komt de lck weer vrij, dus wie weet

**Comment by RobinGeijsel** [comment]
Als er meer ruimte nodig is voor de loco om alles wat zelf tijdens en in de periode vlak na de bouw gedaan wordt kan dit georganiseerd worden. Omdat we niet denken dat dit een lange termijn kwestie is is dit niet opgenomen in het ontwerp.
