### ISSUE TITLE
Is er een uitsplitsing van de 75k voor ‘kosten tijdens de bouw’? Ik heb deze inmiddels redelijk vaak horen langskomen om dingen op te vangen, borrels, peil, etc..:

### ISSUE THREAD

**Issue by wbakkeren** [Plan-van-Bouw/ALV_November_2023#85]
Zet je Financiële vraag in de titel en geef hier indien nodig een uitleg

**Comment by larsdevries6** [comment]
Nee, dit is nog niet gemaakt. Dit omdat wij niet weten wat de mogelijkheden zijn. Wij kunnen bijvoorbeeld de afdracht van het beheer conpenseren, maar we kunnen ook een keet huren en borrels organiseren.
